services:
    _defaults:
        autoconfigure: true

    feopenidprovider.service:
        class: ErikWegner\FeOpenidProvider\Service\AuthorizationServerService
        public: true
        arguments:
            - '@contao.framework'

    feopenidprovider.resourceservice:
        class: ErikWegner\FeOpenidProvider\Service\ResourceServerService
        public: true
        arguments:
            - '@contao.framework'

    ErikWegner\FeOpenidProvider\Controller\AuthCodeController:
        arguments:
            - '@feopenidprovider.service'
            - '@security.helper'
            - '@uri_signer'
        tags:
            - controller.service_arguments
        calls:
            - method: setContainer
              arguments: ['@service_container']

    ErikWegner\FeOpenidProvider\Controller\UserinfoController:
        arguments:
            - '@feopenidprovider.resourceservice'
        tags:
            - controller.service_arguments
        calls:
            - method: setContainer
              arguments: ['@service_container']
